databases:
  - name: rahisisha_development
    ipAllowList: []

services:
  - type: web
    name: Rahisisha Backend
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
     - key: RAILS_MASTER_KEY
       sync: false
     - key: DATABASE_URL
       fromDatabase:
        name: Rahisisha Backend
        property: connectionString